const purgecss = require('@fullhuman/postcss-purgecss')({
  content: [
    './layouts/**/*.html',
  ],
  // These grid area classes are dynamically generated by Hugo
  // so Purgecss doesn't know they will be there.
  whitelist: [
    'article-1',
    'article-2',
    'article-3',
    'article-4',
    'article-5',
    'article-6',
  ],

  // Overriding the default extractor because the default doesn't consider colon
  // and Tailwind makes heavy use of that as a class name.
  defaultExtractor: content => content.match(/[A-Za-z0-9-_:/]+/g) || []
})

module.exports = {
  plugins: [
    require('tailwindcss'),
    require('autoprefixer'),
    purgecss,
  ]
}
