name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true  # Include submodules if your Hugo site uses them

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.111.3'  # Match your Netlify Hugo version
          extended: true  # Use extended Hugo version if needed

      - name: Build
        run: hugo --minify  # Build the site to the 'public' directory

      - name: Upload artifact
        if: github.event_name == 'push'  # Only upload on push, not PRs
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public  # Directory containing the built site

      - name: Deploy to GitHub Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'  # Deploy only on main branch push
        uses: actions/deploy-pages@v4
